ALTER TABLE contractors
  ADD COLUMN IF NOT EXISTS legal_address TEXT,
  ADD COLUMN IF NOT EXISTS actual_address TEXT,
  ADD COLUMN IF NOT EXISTS ogrn VARCHAR(20),
  ADD COLUMN IF NOT EXISTS kpp VARCHAR(20),
  ADD COLUMN IF NOT EXISTS bank_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS bank_corr_account VARCHAR(30),
  ADD COLUMN IF NOT EXISTS bank_bik VARCHAR(20),
  ADD COLUMN IF NOT EXISTS bank_account VARCHAR(30),
  ADD COLUMN IF NOT EXISTS bank_inn VARCHAR(20),
  ADD COLUMN IF NOT EXISTS bank_kpp VARCHAR(20),
  ADD COLUMN IF NOT EXISTS director VARCHAR(255),
  ADD COLUMN IF NOT EXISTS website VARCHAR(255);